;(default)
[input]
MAX_WIDTH         = 3000
REMOVE_BACKGROUND = 0

[sample]
SAMPLE_JIGGLE           = 1

[tracing_path]
SUPER_PIXEL               = 1
NUM_OF_SUPERPIXEL_SEGMENT = 50
CAL_LENGTH                = 0

[scribble]
REDUCE_RADIUS   = 0    ; turn off for demo
CHANGE_NORMAL   = 1
READ_NORMAL_MAP = 0
LINE_WIDTH      = 2
ALPHA_NOISE     = 0.000000
PHI_NOISE       = 0


